#!/bin/fish

alias ls="ls --color=always --group-directories-first"
alias cat="bat"

alias nou="cat $SCRIPTS/Texts/nou.txt | xclip -sel clip"
alias fuckyou="$SCRIPTS/Texts/fuckyou.sh"
alias se="sudoedit"

alias dfiles="/usr/bin/git --git-dir=$HOME/dotfiles.git --work-tree=$HOME"

# Shortened Commands
alias py="python3"
alias nf="neofetch"

# Confirm before overwrite
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"

# Change directory
alias c="cd $CODING && ls"
alias cb="cd $HOME/Scripts && ls"
alias cpy="cd $CODING/Python && ls"
alias cgo="cd $CODING/Go && ls"
alias cr="cd $CODING/Rust && ls"
alias cjs="cd $CODING/JS && ls"
alias pics="cd $PICS && ls"
alias cf="cd $XDG_CONFIG_HOME && ls"
alias ex="cd /mnt/Extra"
alias exb="cd /mnt/Extra/Backups"
alias re="cd $HOME/Repos"
alias rof="cd $XDG_CONFIG_HOME/rofi && ls"

# Open with vim
alias bsp="nvim $XDG_CONFIG_HOME/bspwm/bspwmrc"
alias sx="nvim $XDG_CONFIG_HOME/sxhkd/"
alias frc="nvim $XDG_CONFIG_HOME/fish/config.fish"
alias fa="nvim $XDG_CONFIG_HOME/fish/aliases" 
alias vrc="nvim $XDG_CONFIG_HOME/nvim/init.vim"
alias xrc="nvim $XDG_CONFIG_HOME/X11/xinitrc"
alias poly="nvim $XDG_CONFIG_HOME/polybar/"
alias xr="nvim $XDG_CONFIG_HOME/X11/Xresources"
