#!/bin/bash

# Test for existing DBUS daemon
if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
  eval `dbus-launch --sh-syntax --exit-with-session`
  echo "D-Bus per-session daemon address is: $DBUS_SESSION_BUS_ADDRESS"
fi

# Set path
export PATH=$HOME/.local/bin:$PATH
# Load other vars
export $(cat $HOME/.env | xargs -L 1)

# Audio
exec pipewire &
exec dbus-launch bspwm
