#!/bin/bash

# Set path
export PATH=$HOME/.local/bin:$PATH

# Xrandr
xrandr --output HDMI-A-0 --primary --output DVI-D-0 --right-of HDMI-A-0 --output DisplayPort-0 --above DVI-D-0
# Set cursor
xsetroot -cursor_name left_ptr
sxhkd &

# Other
unclutter -idle 3 &
feh --bg-fill $HOME/.wallpaper.jpg
picom &
wal -n -R &
$HOME/Scripts/System/backuper.sh &

#exec dwm
exec dbus-run-session bspwm
