#!/bin/bash

# -=-=-=-=-=-=-=-=-=-=-= 
#  --- Applications ---
# -=-=-=-=-=-=-=-=-=-=-= 

# Terminal
super + Return
    $TERMINAL -t "$(hostname)@$(whoami)"

# Launcher
super + grave
    $HOME/.config/rofi/launcher.sh

# Browser
super + b
    $BROWSER
super + shift + b
    $BROWSER --private-window

# Ranger
super + r
    $TERMINAL -e ranger $HOME

# Open notes
super + n
    $SCRIPTS/Texts/notes.sh

# Take screenshot
ctrl + shift + backslash
   flameshot gui

# Start/stop record gif
ctrl + shift + BackSpace
    pgrep ffmpeg && killall ffmpeg || $SCRIPTS/Misc/recorder.sh gif

# Quick Open Files
 # super + space
 #    rofi -show file-browser-extended -theme ab-theme -file-browser-dir $HOME -file-browser-depth 10 \
 #        -file-browser-only-files -file-browser-exclude {\.cache,\.cargo,node_modules} \
 #        -file-browser-cmd "$HOME/Scripts/Misc/open-wrapper.sh"
