#!/bin/bash

# -=-=-=-=-=-=-=-=-=-=-= 
#  --- Applications ---
# -=-=-=-=-=-=-=-=-=-=-= 

# Terminal
super + Return
    $TERMINAL -t "$(hostname)@$(whoami)"

# Launcher
super + grave
    $HOME/.config/rofi/launcher.sh

# Browser
super + b
    $BROWSER
super + shift + b
    $BROWSER --private-window

# Ranger
super + r
    $TERMINAL -e ranger $HOME

# Open notes
super + n
    $SCRIPTS/Texts/notes.sh

# Take screenshot
ctrl + shift + backslash
   flameshot gui

# Quick Open Files
super + space
    $SCRIPTS/Misc/rofi-file-launcher.sh
