#!/bin/bash

# -=-=-=-=-=-=-=-=-=-=-= 
#  --- Applications ---
# -=-=-=-=-=-=-=-=-=-=-= 

# Terminal
super + Return
    $TERMINAL -t "$(hostname)@$(whoami)"

# Launcher
super + grave
    rofi -show drun -modi drun -theme ~/.config/rofi/launcher.rasi

# Browser
super + b
    $BROWSER
super + shift + b
    $BROWSER --private-window

# Ranger
super + r
    $TERMINAL -e ranger $HOME

# Open notes
super + n
    $SCRIPTS/Texts/notes.sh

# Take screenshot
ctrl + shift + backslash
   flameshot gui

# Calculator
super + equal
    rofi -show calc -modi calc -no-show-match -no-sort -theme ~/.config/rofi/message.rasi

# Quick google
super + space
    $SCRIPTS/Misc/googler.sh

# Clipboard history
super + c
    rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}' -theme ~/.config/rofi/message.rasi
