#!/bin/bash

# -=-=-=-=-=-=-=-=-=-=-=
#  --- Switch Sinks ---
# -=-=-=-=-=-=-=-=-=-=-=

# Switch to Speakers
ctrl + shift + s
    $SCRIPTS/Audio/switch_speaker.sh
# Switch to Headphones
ctrl + shift + h
    $SCRIPTS/Audio/switch_headphone.sh

# -=-=-=-=-=-=-=-=-=-=-=
#     --- Audio ---
# -=-=-=-=-=-=-=-=-=-=-=

# Volume Up
XF86AudioRaiseVolume
    $SCRIPTS/Audio/audio.sh volup
# Volume Down
XF86AudioLowerVolume
    $SCRIPTS/Audio/audio.sh voldown
# Volume Set
super + XF86AudioRaiseVolume
    $SCRIPTS/Audio/audio.sh volset $VOL
# Toggle Audio Mute
XF86AudioMute
    $SCRIPTS/Audio/audio.sh mute

# -=-=-=-=-=-=-=-=-=-=-=
#  --- Microphone ---
# -=-=-=-=-=-=-=-=-=-=-=

# Toggle Microphone Mute
super + c
    $SCRIPTS/Audio/microphone.sh mute
# Toggle Microphone Hearing
Prior
    $SCRIPTS/Audio/hear-mic-toggle.sh

# -=-=-=-=-=-=-=-=-=-=-=
#   --- Spotify ---
# -=-=-=-=-=-=-=-=-=-=-=

# Pause Spotify
alt + grave
    dbus-send \
    --print-reply \
    --dest=org.mpris.MediaPlayer2.spotify \
    /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause && \
    notify-send -i $ICONS/play-pause-ico.png -t 1500 "Spotify" "Paused/Resumed Playback"
# Skip Spotify
alt + 1
    dbus-send \
    --print-reply \
    --dest=org.mpris.MediaPlayer2.spotify \
    /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
