#!/bin/bash

# -=-=-=-=-=-=-=-=-=-=-= 
#  --- Restart Apps ---
# -=-=-=-=-=-=-=-=-=-=-= 

# SXHDK
super + shift + x
   notify-send "SXHKD Restart" && \ 
    pkill sxhkd && \ 
    sxhkd &

# Polybar
super + shift + p
    $SCRIPTS/System/polybar.sh

# Compositor
super + shift + c
    pgrep -x "picom">/dev/null && pkill picom || picom 


