#!/bin/bash

# -=-=-=-=-=-=-=-=-=-=-= 
#  --- Restart Apps ---
# -=-=-=-=-=-=-=-=-=-=-= 

# SXHDK
super + shift + x
   notify-send -t 3000 "SXHKD Restart" && \
    pkill sxhkd && \
    sxhkd -c $HOME/.config/sxhkd/bspwm \
     $HOME/.config/sxhkd/system \
     $HOME/.config/sxhkd/apps \
     $HOME/.config/sxhkd/audio &

# Polybar
super + shift + p
    $SCRIPTS/System/polybar.sh

# Compositor
super + shift + c
    pgrep -x "picom">/dev/null && pkill picom || picom 


