#!/bin/bash

# --- Rules --- #
bspc rule -r "*"
bspc rule -a Alacritty:AB-Notes state=floating
bspc rule -a Minecraft Launcher:minecraft-launcher state=floating

# --- Monitors --- #
bspc monitor $PRIMARY_DISPLAY -d I II III IV V XI
bspc monitor $SECONDARY_DISPLAY -d VI VII VIII IX X

# -- Global Settings --- #
xrdb $XDG_CONFIG_HOME/X11/Xresources
FOCUS_COLOR=$(xrdb -query | grep "* selected:" | awk '{print $NF}')

bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors false
bspc config remove_unplugged_monitors false
bspc config merge_overlapping_monitors true

bspc config focused_border_color $FOCUS_COLOR

# -- Monitor and Desktop Settings --- #
bspc config top_padding 35
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
#bspc config window_gap 10
