#!/bin/bash

# --- Rules --- #
bspc rule -r "*"
bspc rule -a Alacritty:AB-Notes state=floating

# --- Monitors --- #
bspc monitor HDMI-A-0 -d I II III IV V
bspc monitor DisplayPort-0 -d VI VII VIII IX X

# --- Autostart --- #
# Xrandr
xrandr --output HDMI-A-0 --primary --output DisplayPort-0 --left-of HDMI-A-0 --output DisplayPort-0 --rotate left
# Set cursor
xsetroot -cursor_name left_ptr &
# Hotkey Daemon
sxhkd -c $HOME/.config/sxhkd/bspwm \
    $HOME/.config/sxhkd/system \
    $HOME/.config/sxhkd/apps \
    $HOME/.config/sxhkd/audio &
# Polybar & Theme
$HOME/Scripts/Misc/changetheme.sh cotton_candy &
# Unclutter
unclutter -idle 3 &
# Wallpaper
xwallpaper --zoom .wallpaper.jpg
# Compton
picom &
# Start backup
# $HOME/Scripts/System/backuper.sh &

# -- Global Settings --- #
# Load colors from Xresources
xrdb $HOME/.config/X11/Xresources
FOCUS_COLOR=$(xrdb -query | grep background | cut -f 2 | head -1)

bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors false
bspc config remove_unplugged_monitors false
bspc config merge_overlapping_monitors true

bspc config focused_border_color $FOCUS_COLOR

# -- Monitor and Desktop Settings --- #
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
#bspc config window_gap 10
